# This is a basic workflow to help you get started with Actions

name: Production CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning"

  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
#          key: ${{ secrets.SSHKEY }}
          script: |
            sudo supervisorctl stop ntemtem.api
            cd /home/dev/webapps/ntemtem/backend/Ntemtem.MainService
            eval `ssh-agent`
            ssh-add ~/.ssh/github_id_rsa
            git pull origin main
            dotnet publish --configuration Release
            sudo supervisorctl start ntemtem.api
            sudo supervisorctl status ntemtem.api
            sudo tail -n 30 /var/log/ntemtem.api.out.log
            echo 'Deployment successful to server!'